openapi: 3.0.1
info:
  title: Medical Appointment API
  description: API para agendamiento de citas médicas por país.
  version: 1.0.0

servers:
  - url: https://{api_id}.execute-api.{region}.amazonaws.com/dev
    variables:
      api_id:
        default: your-api-id
      region:
        default: us-east-1

paths:
  /appointments:
    post:
      summary: Registrar agendamiento de cita médica
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - insuredId
                - scheduleId
                - countryISO
              properties:
                insuredId:
                  type: string
                  example: "00123"
                scheduleId:
                  type: integer
                  example: 100
                countryISO:
                  type: string
                  enum: [PE, CL]
                  example: "PE"
      responses:
        "202":
          description: Agendamiento en proceso
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Agendamiento recibido y en proceso"

  /appointments/{insuredId}:
    get:
      summary: Listar citas médicas por código de asegurado
      parameters:
        - name: insuredId
          in: path
          required: true
          schema:
            type: string
            example: "00123"
      responses:
        "200":
          description: Lista de citas agendadas
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    appointmentId:
                      type: string
                      example: "uuid-123"
                    scheduleId:
                      type: integer
                      example: 100
                    status:
                      type: string
                      example: "pending"
                    countryISO:
                      type: string
                      example: "PE"
                    createdAt:
                      type: string
                      format: date-time
                    updatedAt:
                      type: string
                      format: date-time
        "400":
          description: insuredId faltante o inválido
